# Primeira etapa: build
FROM node:20-alpine AS builder
WORKDIR /app
ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Segunda etapa:
FROM alpine:3.19 AS production
WORKDIR /app
COPY --from=builder /app/dist ./dist