version: '3.8'

services:
    postgres-db:
        image: postgres
        container_name: xp-library-db
        restart: always

        environment:
            POSTGRES_USER: 'user'
            POSTGRES_PASSWORD: 'password'
            POSTGRES_DB: 'xp-library'

        ports:
            - "5432:5432"

        volumes:
            - ./pgdata:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: xp-library-pgadmin
        restart: always

        environment:
            PGADMIN_DEFAULT_EMAIL: 'admin@email.com'
            PGADMIN_DEFAULT_PASSWORD: 'admin'

        ports:
            - "5050:80"

        depends_on:
            - postgres-db

